<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.27" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Transcriptions\DownloadTranscript\" />
    <Folder Include="Features\Transcriptions\GetImprovedTranscript\" />
    <Folder Include="Features\Transcriptions\GetRawTranscript\" />
    <Folder Include="Features\Transcriptions\GetTranscriptionStatus\" />
    <Folder Include="Features\Transcriptions\Shared\" />
    <Folder Include="Features\Transcriptions\UploadTranscription\" />
    <Folder Include="Infrastructure\Audio\" />
    <Folder Include="Infrastructure\Configuration\" />
    <Folder Include="Infrastructure\Errors\" />
    <Folder Include="Infrastructure\Export\" />
    <Folder Include="Infrastructure\OpenAI\" />
    <Folder Include="Infrastructure\Storage\" />
  </ItemGroup>

</Project>
